# Barbican Security Module: Observability Stack
#
# Deploys a complete, FedRAMP-compliant observability stack with:
# - Prometheus (metrics collection)
# - Grafana (visualization and dashboards)
# - Loki (log aggregation)
# - Alertmanager (alert routing)
#
# NIST 800-53 Controls:
# - SI-4: Information System Monitoring
# - AU-6: Audit Review, Analysis, and Reporting
# - AU-9: Protection of Audit Information
# - SC-8: Transmission Confidentiality (with TLS)
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.barbican.observability;

  # Profile-specific defaults
  profileDefaults = {
    development = {
      scrapeInterval = "30s";
      retentionDays = 30;
      retentionSize = "10GB";
      tlsEnabled = false;
      authEnabled = false;
    };
    low = {
      scrapeInterval = "30s";
      retentionDays = 30;
      retentionSize = "10GB";
      tlsEnabled = false;
      authEnabled = false;
    };
    moderate = {
      scrapeInterval = "15s";
      retentionDays = 90;
      retentionSize = "50GB";
      tlsEnabled = true;
      authEnabled = true;
    };
    high = {
      scrapeInterval = "10s";
      retentionDays = 365;
      retentionSize = "200GB";
      tlsEnabled = true;
      authEnabled = true;
    };
  };

  defaults = profileDefaults.${cfg.profile} or profileDefaults.development;

  # Generate Prometheus config
  prometheusConfig = pkgs.writeText "prometheus.yml" ''
    # Prometheus Configuration - FedRAMP ${cfg.profile} Profile
    # Generated by barbican.observability module
    # Controls: SI-4 (Monitoring), AU-6 (Audit Analysis)

    global:
      scrape_interval: ${cfg.prometheus.scrapeInterval}
      evaluation_interval: ${cfg.prometheus.scrapeInterval}
      external_labels:
        monitor: '${cfg.appName}-observability'
        environment: 'production'
        fedramp_profile: '${cfg.profile}'

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - localhost:9093
          scheme: http

    rule_files:
      - /etc/prometheus/rules/*.yml

    scrape_configs:
      # Application metrics
      - job_name: '${cfg.appName}'
        static_configs:
          - targets: ['localhost:${toString cfg.appPort}']
        scheme: http
        scrape_interval: ${cfg.prometheus.scrapeInterval}
        metrics_path: /metrics

      # Prometheus self-monitoring
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        scrape_interval: ${cfg.prometheus.scrapeInterval}

      # Loki metrics
      - job_name: 'loki'
        static_configs:
          - targets: ['localhost:3100']
        scheme: http
        scrape_interval: ${cfg.prometheus.scrapeInterval}
        metrics_path: /metrics

      # Grafana metrics
      - job_name: 'grafana'
        static_configs:
          - targets: ['localhost:3000']
        scheme: http
        scrape_interval: ${cfg.prometheus.scrapeInterval}
        metrics_path: /metrics
      ${optionalString (cfg.additionalScrapeConfigs != "") cfg.additionalScrapeConfigs}
  '';

  # Generate Loki config
  lokiConfig = pkgs.writeText "loki-config.yml" ''
    # Loki Configuration - FedRAMP ${cfg.profile} Profile
    # Generated by barbican.observability module
    # Control: AU-9 (Protection of Audit Information)

    auth_enabled: ${boolToString cfg.loki.authEnabled}

    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3100
      grpc_listen_port: 9096
      log_level: info

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki/data
      storage:
        filesystem:
          chunks_directory: /loki/data/chunks
          rules_directory: /loki/data/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    limits_config:
      retention_period: ${toString cfg.loki.retentionDays}d
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_query_series: 5000
      max_query_parallelism: 32

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/data/tsdb-index
        cache_location: /loki/data/tsdb-cache
        cache_ttl: 24h

    compactor:
      working_directory: /loki/data/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: filesystem

    analytics:
      reporting_enabled: false
  '';

  # Generate Grafana datasources
  grafanaDatasources = pkgs.writeText "datasources.yml" ''
    # Grafana Datasource Provisioning - FedRAMP ${cfg.profile} Profile
    # Control: AU-6 (Audit Review, Analysis, Reporting)

    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://localhost:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          httpMethod: POST

      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://localhost:3100
        isDefault: false
        editable: false
        jsonData:
          maxLines: 1000

      - name: Alertmanager
        type: alertmanager
        uid: alertmanager
        access: proxy
        url: http://localhost:9093
        isDefault: false
        editable: false
        jsonData:
          implementation: prometheus
  '';

  # Generate Grafana dashboard provisioning
  grafanaDashboards = pkgs.writeText "dashboards.yml" ''
    apiVersion: 1

    providers:
      - name: 'default'
        orgId: 1
        folder: 'Security'
        folderUid: 'security'
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        allowUiUpdates: false
        options:
          path: /etc/grafana/provisioning/dashboards/json
  '';

  # Generate Alertmanager config
  alertmanagerConfig = pkgs.writeText "alertmanager.yml" ''
    # Alertmanager Configuration - FedRAMP ${cfg.profile} Profile
    # Control: IR-4 (Incident Handling)

    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'default'
      routes:
        - match:
            severity: critical
          receiver: 'critical'
          group_wait: 10s
        - match:
            severity: warning
          receiver: 'warning'

    receivers:
      - name: 'default'
        # Configure your notification channels here
      - name: 'critical'
        # Configure critical alerts (PagerDuty, etc.)
      - name: 'warning'
        # Configure warning alerts (Slack, email, etc.)

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']
  '';

  # Generate Grafana INI
  grafanaIni = pkgs.writeText "grafana.ini" ''
    # Grafana Configuration - FedRAMP ${cfg.profile} Profile
    # Controls: IA-2, AC-2, AC-11, AC-12

    [server]
    protocol = http
    http_addr = 0.0.0.0
    http_port = 3000
    root_url = ${cfg.grafana.rootUrl}
    enable_gzip = true

    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db

    [security]
    admin_user = ${cfg.grafana.adminUser}
    admin_password = ''${GF_SECURITY_ADMIN_PASSWORD}
    secret_key = ''${GF_SECURITY_SECRET_KEY}
    cookie_secure = false
    cookie_samesite = strict

    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Viewer

    [auth]
    disable_login_form = false
    disable_signout_menu = false

    [auth.anonymous]
    enabled = ${boolToString cfg.grafana.anonymousEnabled}
    org_role = ${cfg.grafana.anonymousRole}

    [log]
    mode = console
    level = info

    [log.console]
    format = json

    [metrics]
    enabled = true

    [analytics]
    reporting_enabled = false
    check_for_updates = false
  '';

  # Generate docker-compose.yml for container deployment
  dockerComposeConfig = pkgs.writeText "docker-compose.yml" ''
    # Observability Stack - FedRAMP ${cfg.profile} Profile
    # Generated by barbican.observability module

    services:
      loki-init:
        image: alpine:3.19
        container_name: ${cfg.appName}-loki-init
        command: sh -c "mkdir -p /data/chunks /data/rules /data/tsdb-index /data/tsdb-cache /data/compactor && chown -R 10001:10001 /data"
        volumes:
          - ${cfg.appName}_loki_data:/data
        user: root
        restart: "no"

      prometheus-init:
        image: alpine:3.19
        container_name: ${cfg.appName}-prometheus-init
        command: sh -c "chown -R 65534:65534 /data"
        volumes:
          - ${cfg.appName}_prometheus_data:/data
        user: root
        restart: "no"

      grafana-init:
        image: alpine:3.19
        container_name: ${cfg.appName}-grafana-init
        command: sh -c "chown -R 472:472 /data"
        volumes:
          - ${cfg.appName}_grafana_data:/data
        user: root
        restart: "no"

      alertmanager-init:
        image: alpine:3.19
        container_name: ${cfg.appName}-alertmanager-init
        command: sh -c "chown -R 65534:65534 /data"
        volumes:
          - ${cfg.appName}_alertmanager_data:/data
        user: root
        restart: "no"

      loki:
        image: grafana/loki:2.9.2
        container_name: ${cfg.appName}-loki
        restart: always
        command: -config.file=/etc/loki/loki-config.yml
        volumes:
          - loki-config:/etc/loki:ro
          - ${cfg.appName}_loki_data:/loki/data
        ports:
          - "${cfg.loki.bindAddress}:3100:3100"
        depends_on:
          loki-init:
            condition: service_completed_successfully
        healthcheck:
          test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
          interval: 15s
          timeout: 5s
          retries: 3
          start_period: 30s
        deploy:
          resources:
            limits:
              memory: 1g

      prometheus:
        image: prom/prometheus:v2.47.2
        container_name: ${cfg.appName}-prometheus
        restart: always
        network_mode: host
        depends_on:
          prometheus-init:
            condition: service_completed_successfully
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--storage.tsdb.retention.time=${toString cfg.prometheus.retentionDays}d'
          - '--storage.tsdb.retention.size=${cfg.prometheus.retentionSize}'
          - '--web.enable-lifecycle'
          - '--web.enable-admin-api'
          - '--web.listen-address=${cfg.prometheus.bindAddress}:9090'
        volumes:
          - prometheus-config:/etc/prometheus:ro
          - ${cfg.appName}_prometheus_data:/prometheus
        healthcheck:
          test: ["CMD-SHELL", "wget -q --spider http://localhost:9090/-/ready || exit 1"]
          interval: 15s
          timeout: 5s
          retries: 3
          start_period: 30s
        deploy:
          resources:
            limits:
              memory: 1g

      grafana:
        image: grafana/grafana:10.2.2
        container_name: ${cfg.appName}-grafana
        restart: always
        network_mode: host
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=${cfg.grafana.adminPassword}
          - GF_SECURITY_SECRET_KEY=${cfg.grafana.secretKey}
        volumes:
          - grafana-config:/etc/grafana:ro
          - ${cfg.appName}_grafana_data:/var/lib/grafana
        depends_on:
          grafana-init:
            condition: service_completed_successfully
        healthcheck:
          test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
          interval: 15s
          timeout: 5s
          retries: 3
          start_period: 60s
        deploy:
          resources:
            limits:
              memory: 512m

      alertmanager:
        image: prom/alertmanager:v0.26.0
        container_name: ${cfg.appName}-alertmanager
        restart: always
        depends_on:
          alertmanager-init:
            condition: service_completed_successfully
        command:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
          - '--web.listen-address=${cfg.alertmanager.bindAddress}:9093'
        volumes:
          - alertmanager-config:/etc/alertmanager:ro
          - ${cfg.appName}_alertmanager_data:/alertmanager
        ports:
          - "${cfg.alertmanager.bindAddress}:9093:9093"
        healthcheck:
          test: ["CMD-SHELL", "wget -q --spider http://localhost:9093/-/ready || exit 1"]
          interval: 15s
          timeout: 5s
          retries: 3
          start_period: 15s
        deploy:
          resources:
            limits:
              memory: 256m

    volumes:
      ${cfg.appName}_loki_data:
      ${cfg.appName}_prometheus_data:
      ${cfg.appName}_grafana_data:
      ${cfg.appName}_alertmanager_data:
      loki-config:
        external: true
      prometheus-config:
        external: true
      grafana-config:
        external: true
      alertmanager-config:
        external: true
  '';

  # Setup script that prepares configs and starts the stack
  observabilitySetupScript = pkgs.writeShellScript "observability-setup" ''
    set -euo pipefail

    CONFIG_DIR="/var/lib/observability"
    mkdir -p "$CONFIG_DIR"/{prometheus/rules,loki,grafana/provisioning/datasources,grafana/provisioning/dashboards/json,alertmanager}

    # Copy generated configs
    cp ${prometheusConfig} "$CONFIG_DIR/prometheus/prometheus.yml"
    cp ${lokiConfig} "$CONFIG_DIR/loki/loki-config.yml"
    cp ${grafanaDatasources} "$CONFIG_DIR/grafana/provisioning/datasources/datasources.yml"
    cp ${grafanaDashboards} "$CONFIG_DIR/grafana/provisioning/dashboards/dashboards.yml"
    cp ${grafanaIni} "$CONFIG_DIR/grafana/grafana.ini"
    cp ${alertmanagerConfig} "$CONFIG_DIR/alertmanager/alertmanager.yml"

    # Copy additional rules if provided
    ${optionalString (cfg.prometheus.rulesPath != null) ''
      cp -r ${cfg.prometheus.rulesPath}/* "$CONFIG_DIR/prometheus/rules/" 2>/dev/null || true
    ''}

    # Copy additional dashboards if provided
    ${optionalString (cfg.grafana.dashboardsPath != null) ''
      cp -r ${cfg.grafana.dashboardsPath}/* "$CONFIG_DIR/grafana/provisioning/dashboards/json/" 2>/dev/null || true
    ''}

    # Set permissions
    chmod -R 755 "$CONFIG_DIR"

    echo "Observability configs prepared in $CONFIG_DIR"
  '';

  # Script to start the observability stack via Podman
  observabilityStartScript = pkgs.writeShellScript "observability-start" ''
    set -euo pipefail

    # Ensure configs are ready
    ${observabilitySetupScript}

    CONFIG_DIR="/var/lib/observability"

    # Create podman volumes and copy configs
    ${pkgs.podman}/bin/podman volume create loki-config 2>/dev/null || true
    ${pkgs.podman}/bin/podman volume create prometheus-config 2>/dev/null || true
    ${pkgs.podman}/bin/podman volume create grafana-config 2>/dev/null || true
    ${pkgs.podman}/bin/podman volume create alertmanager-config 2>/dev/null || true

    # Copy configs to volumes using a helper container
    ${pkgs.podman}/bin/podman run --rm \
      -v loki-config:/dest \
      -v "$CONFIG_DIR/loki:/src:ro" \
      alpine:3.19 sh -c "cp -r /src/* /dest/"

    ${pkgs.podman}/bin/podman run --rm \
      -v prometheus-config:/dest \
      -v "$CONFIG_DIR/prometheus:/src:ro" \
      alpine:3.19 sh -c "cp -r /src/* /dest/"

    ${pkgs.podman}/bin/podman run --rm \
      -v grafana-config:/dest \
      -v "$CONFIG_DIR/grafana:/src:ro" \
      alpine:3.19 sh -c "cp -r /src/* /dest/"

    ${pkgs.podman}/bin/podman run --rm \
      -v alertmanager-config:/dest \
      -v "$CONFIG_DIR/alertmanager:/src:ro" \
      alpine:3.19 sh -c "cp -r /src/* /dest/"

    # Start the stack
    cd /var/lib/observability
    ${pkgs.podman-compose}/bin/podman-compose -f ${dockerComposeConfig} up -d

    echo "Observability stack started"
    echo "  Prometheus: http://${cfg.prometheus.bindAddress}:9090"
    echo "  Grafana:    http://${cfg.grafana.bindAddress}:3000"
    echo "  Loki:       http://${cfg.loki.bindAddress}:3100"
    echo "  Alertmanager: http://${cfg.alertmanager.bindAddress}:9093"
  '';

in {
  options.barbican.observability = {
    enable = mkEnableOption "Barbican observability stack";

    profile = mkOption {
      type = types.enum [ "development" "low" "moderate" "high" ];
      default = "development";
      description = ''
        FedRAMP compliance profile. Controls retention, scrape intervals, and security settings.
        - development: No auth, 30-day retention
        - low: Basic security, 30-day retention
        - moderate: Auth enabled, 90-day retention, TLS recommended
        - high: Full security, 365-day retention, TLS required
      '';
    };

    appName = mkOption {
      type = types.str;
      default = "app";
      description = "Application name for labels and container naming";
    };

    appPort = mkOption {
      type = types.port;
      default = 8080;
      description = "Port where the application exposes metrics";
    };

    # Prometheus options
    prometheus = {
      bindAddress = mkOption {
        type = types.str;
        default = "0.0.0.0";
        description = ''
          Address for Prometheus to listen on.
          Defaults to 0.0.0.0 to support VM/container port forwarding.
        '';
      };

      scrapeInterval = mkOption {
        type = types.str;
        default = defaults.scrapeInterval;
        description = "How often to scrape metrics";
      };

      retentionDays = mkOption {
        type = types.int;
        default = defaults.retentionDays;
        description = "How long to retain metrics data";
      };

      retentionSize = mkOption {
        type = types.str;
        default = defaults.retentionSize;
        description = "Maximum storage size for metrics";
      };

      rulesPath = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = "Path to directory containing Prometheus alerting rules";
      };
    };

    # Grafana options
    grafana = {
      bindAddress = mkOption {
        type = types.str;
        default = "0.0.0.0";
        description = "Address for Grafana to listen on";
      };

      rootUrl = mkOption {
        type = types.str;
        default = "http://localhost:3000";
        description = "Root URL for Grafana (for OAuth callbacks, etc.)";
      };

      adminUser = mkOption {
        type = types.str;
        default = "admin";
        description = "Grafana admin username";
      };

      adminPassword = mkOption {
        type = types.str;
        default = "admin";
        description = "Grafana admin password (use environment variable in production)";
      };

      secretKey = mkOption {
        type = types.str;
        default = "dev-secret-key";
        description = "Secret key for signing cookies (use environment variable in production)";
      };

      anonymousEnabled = mkOption {
        type = types.bool;
        default = cfg.profile == "development";
        description = "Enable anonymous access (defaults to true for development)";
      };

      anonymousRole = mkOption {
        type = types.enum [ "Viewer" "Editor" "Admin" ];
        default = if cfg.profile == "development" then "Admin" else "Viewer";
        description = "Role for anonymous users";
      };

      dashboardsPath = mkOption {
        type = types.nullOr types.path;
        default = null;
        description = "Path to directory containing dashboard JSON files";
      };
    };

    # Loki options
    loki = {
      bindAddress = mkOption {
        type = types.str;
        default = "0.0.0.0";
        description = "Address for Loki to listen on";
      };

      authEnabled = mkOption {
        type = types.bool;
        default = defaults.authEnabled;
        description = "Enable multi-tenancy authentication";
      };

      retentionDays = mkOption {
        type = types.int;
        default = defaults.retentionDays;
        description = "How long to retain log data";
      };
    };

    # Alertmanager options
    alertmanager = {
      bindAddress = mkOption {
        type = types.str;
        default = "0.0.0.0";
        description = "Address for Alertmanager to listen on";
      };
    };

    # Additional scrape configs (YAML string)
    additionalScrapeConfigs = mkOption {
      type = types.str;
      default = "";
      description = "Additional Prometheus scrape configurations in YAML format";
    };
  };

  config = mkIf cfg.enable {
    # Ensure Podman is available
    virtualisation.podman = {
      enable = true;
      dockerCompat = true;
    };

    # Add required packages
    environment.systemPackages = with pkgs; [
      podman-compose
    ];

    # Create data directories
    systemd.tmpfiles.rules = [
      "d /var/lib/observability 0755 root root -"
      "d /var/lib/observability/prometheus 0755 root root -"
      "d /var/lib/observability/prometheus/rules 0755 root root -"
      "d /var/lib/observability/grafana 0755 root root -"
      "d /var/lib/observability/grafana/provisioning 0755 root root -"
      "d /var/lib/observability/grafana/provisioning/datasources 0755 root root -"
      "d /var/lib/observability/grafana/provisioning/dashboards 0755 root root -"
      "d /var/lib/observability/grafana/provisioning/dashboards/json 0755 root root -"
      "d /var/lib/observability/loki 0755 root root -"
      "d /var/lib/observability/alertmanager 0755 root root -"
    ];

    # Systemd service to start observability stack
    systemd.services.barbican-observability = {
      description = "Barbican Observability Stack";
      after = [ "network.target" "podman.service" ];
      wants = [ "podman.service" ];
      wantedBy = [ "multi-user.target" ];

      # podman-compose internally calls 'podman' as a subprocess
      path = [ pkgs.podman ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${observabilityStartScript}";
        ExecStop = "${pkgs.podman-compose}/bin/podman-compose -f ${dockerComposeConfig} down";
      };
    };

    # Firewall rules
    networking.firewall.allowedTCPPorts = [
      9090  # Prometheus
      3000  # Grafana
      3100  # Loki
      9093  # Alertmanager
    ];
  };
}
